export const INSTRUMENT_EVENT_TYPE = {
  INSTRUMENT_CREATED: "INSTRUMENT_CREATED",
  INSTRUMENT_VERSION_CREATED: "INSTRUMENT_VERSION_CREATED",
  INSTRUMENT_VERSION_ISSUED: "INSTRUMENT_VERSION_ISSUED",

  INSTRUMENT_ACCESS_GRANTED: "INSTRUMENT_ACCESS_GRANTED",
  INSTRUMENT_ACCESSED: "INSTRUMENT_ACCESSED",
  INSTRUMENT_ACCESS_REVOKED: "INSTRUMENT_ACCESS_REVOKED",

  INSTRUMENT_PROPOSITION_DEFINED: "INSTRUMENT_PROPOSITION_DEFINED",

  INSTRUMENT_RESPONSE_RECORDED: "INSTRUMENT_RESPONSE_RECORDED",
  INSTRUMENT_RESPONSE_SUPERSEDED: "INSTRUMENT_RESPONSE_SUPERSEDED",

  INSTRUMENT_STATUS_CHANGED: "INSTRUMENT_STATUS_CHANGED",

  INSTRUMENT_AUTHORITY_RECORDED: "INSTRUMENT_AUTHORITY_RECORDED",
  INSTRUMENT_AUTHORITY_REVOKED: "INSTRUMENT_AUTHORITY_REVOKED",
  INSTRUMENT_STATE_TRANSITION_RECORDED:
    "INSTRUMENT_STATE_TRANSITION_RECORDED",
  INSTRUMENT_EVIDENCE_RECORDED:
    "INSTRUMENT_EVIDENCE_RECORDED",
  INSTRUMENT_RELATION_CREATED:
    "INSTRUMENT_RELATION_CREATED",

  SETTLEMENT_INSTRUCTION_DEFINED: "SETTLEMENT_INSTRUCTION_DEFINED",
  SETTLEMENT_INSTRUCTION_ISSUED: "SETTLEMENT_INSTRUCTION_ISSUED",
  SETTLEMENT_VERIFICATION_CONFIRMED: "SETTLEMENT_VERIFICATION_CONFIRMED",
  SETTLEMENT_PRINCIPAL_AUTHORIZED: "SETTLEMENT_PRINCIPAL_AUTHORIZED",
  SETTLEMENT_STATUS_CHANGED: "SETTLEMENT_STATUS_CHANGED",
} as const;

export type InstrumentEventType =
  (typeof INSTRUMENT_EVENT_TYPE)[keyof typeof INSTRUMENT_EVENT_TYPE];
