export const INSTRUMENT_EVENT_TYPE = {
  INSTRUMENT_CREATED: "INSTRUMENT_CREATED",
  INSTRUMENT_VERSION_CREATED: "INSTRUMENT_VERSION_CREATED",
  INSTRUMENT_VERSION_ISSUED: "INSTRUMENT_VERSION_ISSUED",
  INSTRUMENT_VERSION_SUPERSEDED: "INSTRUMENT_VERSION_SUPERSEDED",

  INSTRUMENT_ACCESS_GRANTED: "INSTRUMENT_ACCESS_GRANTED",
  INSTRUMENT_ACCESSED: "INSTRUMENT_ACCESSED",
  INSTRUMENT_ACCESS_REVOKED: "INSTRUMENT_ACCESS_REVOKED",

  INSTRUMENT_PROPOSITION_DEFINED: "INSTRUMENT_PROPOSITION_DEFINED",

  INSTRUMENT_RESPONSE_RECORDED: "INSTRUMENT_RESPONSE_RECORDED",
  INSTRUMENT_RESPONSE_SUPERSEDED: "INSTRUMENT_RESPONSE_SUPERSEDED",

  INSTRUMENT_STATUS_CHANGED: "INSTRUMENT_STATUS_CHANGED",

  SETTLEMENT_INSTRUCTION_DEFINED: "SETTLEMENT_INSTRUCTION_DEFINED",
  SETTLEMENT_INSTRUCTION_ISSUED: "SETTLEMENT_INSTRUCTION_ISSUED",
  SETTLEMENT_PRICE_FIXED: "SETTLEMENT_PRICE_FIXED",
  SETTLEMENT_VERIFICATION_RECOGNIZED: "SETTLEMENT_VERIFICATION_RECOGNIZED",
  SETTLEMENT_PRINCIPAL_AUTHORIZED: "SETTLEMENT_PRINCIPAL_AUTHORIZED",
  SETTLEMENT_STATUS_CHANGED: "SETTLEMENT_STATUS_CHANGED",
} as const;

export type InstrumentEventType =
  (typeof INSTRUMENT_EVENT_TYPE)[keyof typeof INSTRUMENT_EVENT_TYPE];
