export const TREASURY_AGGREGATE_TYPE = {
  COMMERCIAL_PROGRAM: "COMMERCIAL_PROGRAM",

  TREASURY_ACTOR: "TREASURY_ACTOR",

  TREASURY_AUTHORITY_GRANT: "TREASURY_AUTHORITY_GRANT",

  TREASURY_PARTY: "TREASURY_PARTY",

  BENEFICIARY_PROFILE: "BENEFICIARY_PROFILE",

  PROGRAM_CAPITAL_RECEIPT: "PROGRAM_CAPITAL_RECEIPT",

  TREASURY_INSTRUCTION: "TREASURY_INSTRUCTION",

  TREASURY_TRANSFER: "TREASURY_TRANSFER",

  TRANSFER_AUTHORITY_ASSESSMENT: "TRANSFER_AUTHORITY_ASSESSMENT",

  TRANSFER_CAPACITY_ASSESSMENT: "TRANSFER_CAPACITY_ASSESSMENT",

  TREASURY_ALLOCATION: "TREASURY_ALLOCATION",

  TREASURY_RESERVE: "TREASURY_RESERVE",

  DISTRIBUTION_BATCH: "DISTRIBUTION_BATCH",

  DISTRIBUTION_ITEM: "DISTRIBUTION_ITEM",

  TREASURY_EXECUTION: "TREASURY_EXECUTION",

  TREASURY_RECONCILIATION_PASS: "TREASURY_RECONCILIATION_PASS",

  TREASURY_APPROVAL: "TREASURY_APPROVAL",

  TREASURY_JOURNAL_ENTRY: "TREASURY_JOURNAL_ENTRY",
} as const;

export type TreasuryAggregateType =
  (typeof TREASURY_AGGREGATE_TYPE)[keyof typeof TREASURY_AGGREGATE_TYPE];
