export const TREASURY_EVENT_TYPE = {
  CAPITAL_RECEIPT_REPORTED: "CAPITAL_RECEIPT_REPORTED",

  CAPITAL_RECEIPT_VERIFICATION_STARTED: "CAPITAL_RECEIPT_VERIFICATION_STARTED",

  CAPITAL_RECEIPT_VERIFIED: "CAPITAL_RECEIPT_VERIFIED",

  CAPITAL_RECEIPT_REJECTED: "CAPITAL_RECEIPT_REJECTED",

  PROGRAM_CAPITAL_RECOGNIZED: "PROGRAM_CAPITAL_RECOGNIZED",

  PROGRAM_CAPITAL_RECOGNITION_REVERSED: "PROGRAM_CAPITAL_RECOGNITION_REVERSED",

  TREASURY_INSTRUCTION_SUBMITTED: "TREASURY_INSTRUCTION_SUBMITTED",

  TREASURY_INSTRUCTION_AUTHORITY_REVIEW_STARTED:
    "TREASURY_INSTRUCTION_AUTHORITY_REVIEW_STARTED",

  TREASURY_INSTRUCTION_AUTHENTICATED: "TREASURY_INSTRUCTION_AUTHENTICATED",

  TREASURY_INSTRUCTION_REVIEW_STARTED: "TREASURY_INSTRUCTION_REVIEW_STARTED",

  TREASURY_INSTRUCTION_CLARIFICATION_REQUESTED:
    "TREASURY_INSTRUCTION_CLARIFICATION_REQUESTED",

  TREASURY_INSTRUCTION_APPROVED: "TREASURY_INSTRUCTION_APPROVED",

  TREASURY_INSTRUCTION_REJECTED: "TREASURY_INSTRUCTION_REJECTED",

  TREASURY_INSTRUCTION_CANCELLED: "TREASURY_INSTRUCTION_CANCELLED",

  TREASURY_INSTRUCTION_FULFILLED: "TREASURY_INSTRUCTION_FULFILLED",

  TREASURY_INSTRUCTION_SUPERSEDED: "TREASURY_INSTRUCTION_SUPERSEDED",

  TREASURY_ALLOCATION_CREATED: "TREASURY_ALLOCATION_CREATED",

  TREASURY_ALLOCATION_REVIEW_STARTED: "TREASURY_ALLOCATION_REVIEW_STARTED",

  TREASURY_ALLOCATION_APPROVED: "TREASURY_ALLOCATION_APPROVED",

  TREASURY_ALLOCATION_ACTIVATED: "TREASURY_ALLOCATION_ACTIVATED",

  TREASURY_ALLOCATION_CONSUMED: "TREASURY_ALLOCATION_CONSUMED",

  TREASURY_ALLOCATION_RELEASED: "TREASURY_ALLOCATION_RELEASED",

  TREASURY_EXECUTION_CREATED: "TREASURY_EXECUTION_CREATED",

  TREASURY_EXECUTION_AUTHORIZED: "TREASURY_EXECUTION_AUTHORIZED",

  TREASURY_EXECUTION_INITIATED: "TREASURY_EXECUTION_INITIATED",

  TREASURY_EXECUTION_CONFIRMED: "TREASURY_EXECUTION_CONFIRMED",

  TREASURY_EXECUTION_FAILED: "TREASURY_EXECUTION_FAILED",
} as const;

export type TreasuryEventType =
  (typeof TREASURY_EVENT_TYPE)[keyof typeof TREASURY_EVENT_TYPE];
