export const ESCROW_STATUS = {
  INITIATED: "INITIATED",
  FUNDS_LOCKED: "FUNDS_LOCKED",
  AWAITING_CONDITION: "AWAITING_CONDITION",
  DISPUTED: "DISPUTED",
  RELEASE_APPROVED: "RELEASE_APPROVED",
  RELEASED: "RELEASED",
  CANCELLED: "CANCELLED",
  SETTLED: "SETTLED",
} as const

export type EscrowStatus =
  typeof ESCROW_STATUS[keyof typeof ESCROW_STATUS]