export const ESCROW_STATUS = {
  INITIATED: "INITIATED",
  ACTIVE: "ACTIVE",
  FUNDS_LOCKED: "FUNDS_LOCKED",
  DISPUTED: "DISPUTED",
  ARBITRATED: "ARBITRATED",
  RELEASED: "RELEASED",
  CANCELLED: "CANCELLED",
  SETTLED: "SETTLED",
} as const

export type EscrowStatus =
  typeof ESCROW_STATUS[keyof typeof ESCROW_STATUS]
