export const TREASURY_ACTION_STATUS = {
  PENDING: 'PENDING',

  APPROVED: 'APPROVED',

  QUEUED: 'QUEUED',

  EXECUTING: 'EXECUTING',

  EXECUTED: 'EXECUTED',

  FAILED_RETRYABLE: 'FAILED_RETRYABLE',

  FAILED_TERMINAL: 'FAILED_TERMINAL',

  REJECTED: 'REJECTED',

  CANCELLED: 'CANCELLED',
} as const

export type TreasuryActionStatus =
  (typeof TREASURY_ACTION_STATUS)[keyof typeof TREASURY_ACTION_STATUS]

export const TREASURY_QUEUE_STATUS = {
  PENDING: 'PENDING',

  CLAIMED: 'CLAIMED',

  EXECUTING: 'EXECUTING',

  EXECUTED: 'EXECUTED',

  FAILED_RETRYABLE: 'FAILED_RETRYABLE',

  FAILED_TERMINAL: 'FAILED_TERMINAL',

  CANCELLED: 'CANCELLED',
} as const

export type TreasuryQueueStatus =
  (typeof TREASURY_QUEUE_STATUS)[keyof typeof TREASURY_QUEUE_STATUS]
