export const EventTypes = {
  TREASURY_INFLOW: "TREASURY_INFLOW",
  TREASURY_OUTFLOW: "TREASURY_OUTFLOW",

  ESCROW_FUNDED: "ESCROW_FUNDED",
  ESCROW_PARTIALLY_FUNDED: "ESCROW_PARTIALLY_FUNDED",
  ESCROW_RELEASED: "ESCROW_RELEASED",
  ESCROW_MISMATCH: "ESCROW_MISMATCH",

  // ✅ REQUIRED (you are using these now)
  ESCROW_LOCKED: "ESCROW_LOCKED",
  CASE_FLAGGED: "CASE_FLAGGED",
  ACTION_REVERSED: "ACTION_REVERSED",

  CASE_CREATED: "CASE_CREATED",
  GATES_INITIALIZED: "GATES_INITIALIZED",
  ARTIFACTS_REQUIRED: "ARTIFACTS_REQUIRED",
} as const

export type EventType = (typeof EventTypes)[keyof typeof EventTypes]