export const TREASURY_TRANSFER_STATUS = {
  CREATED: "CREATED",

  AUTHORITY_REVIEW: "AUTHORITY_REVIEW",

  AUTHORIZED: "AUTHORIZED",

  REQUIRES_CLARIFICATION: "REQUIRES_CLARIFICATION",

  REJECTED: "REJECTED",

  CAPACITY_ASSESSED: "CAPACITY_ASSESSED",

  CAPACITY_UNDETERMINED: "CAPACITY_UNDETERMINED",
} as const;

export type TreasuryTransferStatus =
  (typeof TREASURY_TRANSFER_STATUS)[keyof typeof TREASURY_TRANSFER_STATUS];
