export const COMMUNICATION_EVENT_TYPE = {
  CONVERSATION_CREATED:
    "COMMUNICATION_CONVERSATION_CREATED",

  MEMBER_ADDED:
    "COMMUNICATION_MEMBER_ADDED",

  MESSAGE_SENT:
    "COMMUNICATION_MESSAGE_SENT",

  CONVERSATION_ARCHIVED:
    "COMMUNICATION_CONVERSATION_ARCHIVED",

  CONVERSATION_REACTIVATED:
    "COMMUNICATION_CONVERSATION_REACTIVATED",
} as const

export type CommunicationEventType =
  (typeof COMMUNICATION_EVENT_TYPE)[keyof typeof COMMUNICATION_EVENT_TYPE]
