export const PROGRAM_CAPITAL_RECEIPT_STATUS = {
  DRAFT: "DRAFT",

  EXPECTED: "EXPECTED",

  REPORTED: "REPORTED",

  UNDER_VERIFICATION: "UNDER_VERIFICATION",

  VERIFIED: "VERIFIED",

  RECOGNIZED: "RECOGNIZED",

  REJECTED: "REJECTED",

  REVERSED: "REVERSED",
} as const;

export type ProgramCapitalReceiptStatus =
  (typeof PROGRAM_CAPITAL_RECEIPT_STATUS)[keyof typeof PROGRAM_CAPITAL_RECEIPT_STATUS];
