-- AlterTable
ALTER TABLE "OperatorTrust" ADD COLUMN     "influenceScore" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "respectScore" DOUBLE PRECISION NOT NULL DEFAULT 1,
ALTER COLUMN "lastUpdatedAt" DROP DEFAULT;
