export const dossierTransitions = {
  INTAKE_PENDING: ["KYC_REVIEW"],

  KYC_REVIEW: ["SPA_DRAFTING", "BLOCKED"],

  SPA_DRAFTING: ["SPA_EXECUTED", "CANCELLED"],

  SPA_EXECUTED: [
    "ESCROW_PENDING",
    "PAYMENT_INSTRUCTION_PENDING",
    "CRYPTO_WALLET_CONFIRMATION",
    "FINANCIAL_INSTRUMENT_PENDING",
    "REFINERY_COORDINATION",
    "BLOCKED",
  ],

  ESCROW_PENDING: ["ESCROW_FUNDED", "BLOCKED"],

  ESCROW_FUNDED: ["TREASURY_PENDING"],

  PAYMENT_INSTRUCTION_PENDING: ["PAYMENT_CONFIRMED", "BLOCKED"],

  PAYMENT_CONFIRMED: ["TREASURY_PENDING"],

  CRYPTO_WALLET_CONFIRMATION: ["CRYPTO_RECEIVED", "BLOCKED"],

  CRYPTO_RECEIVED: ["TREASURY_PENDING"],

  FINANCIAL_INSTRUMENT_PENDING: ["FINANCIAL_INSTRUMENT_CONFIRMED", "BLOCKED"],

  FINANCIAL_INSTRUMENT_CONFIRMED: ["TREASURY_PENDING"],

  REFINERY_COORDINATION: ["EXPORT_RELEASED", "BLOCKED"],

  TREASURY_PENDING: ["EXPORT_RELEASED"],

  EXPORT_RELEASED: ["EXPORT_ACTIVE"],

  EXPORT_ACTIVE: ["IN_TRANSIT"],

  IN_TRANSIT: ["REFINERY_INTAKE"],

  REFINERY_INTAKE: ["REFINERY_ASSAY"],

  REFINERY_ASSAY: ["ASSAY_PENDING"],

  ASSAY_PENDING: ["SETTLEMENT_PENDING"],

  SETTLEMENT_PENDING: ["SETTLED"],

  SETTLED: ["CLOSED"],

  BLOCKED: [],
  CANCELLED: [],
  CLOSED: [],
} as const;

export type DossierState = keyof typeof dossierTransitions;

export function getNextDossierStates(state: string): string[] {
  return [...(dossierTransitions[state as DossierState] ?? [])];
}

export function canTransitionDossier(
  fromState: string,
  toState: string,
): boolean {
  const allowed = getNextDossierStates(fromState);

  return allowed.includes(toState);
}
