[profile.default]
# Project root is the repo root (no --root flag needed)
src    = "contracts/contracts"
script = "contracts/script"
out    = "out"
libs   = ["lib"]

# Compiler/optimizer
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = false

# Remappings (so Etherscan + local compiler can resolve OZ paths)
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

# RPC (Foundry reads SEPOLIA_RPC_URL from env)
rpc_endpoints = { sepolia = "${SEPOLIA_RPC_URL}" }

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }