[profile.default]
src = "contracts/src"
script = "contracts/script"
out = "out"
libs = ["contracts/lib","lib"]
optimizer = true
optimizer_runs = 200
solc = "0.8.28"

rpc_endpoints = { sepolia = "${SEPOLIA_RPC_URL}" }

remappings = [
  "@openzeppelin/contracts/=contracts/lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/=contracts/lib/chainlink-brownie-contracts/contracts/",
  "openzeppelin-contracts/=contracts/lib/openzeppelin-contracts/",
  "chainlink-brownie-contracts/=contracts/lib/chainlink-brownie-contracts/",
  "forge-std/=contracts/lib/forge-std/src/",
  "ds-test/=contracts/lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/",
  "erc4626-tests/=contracts/lib/openzeppelin-contracts/lib/erc4626-tests/"
]

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }