[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",  # If using OpenZeppelin
    "chainlink-contracts/=lib/chainlink-contracts/src/"         # If using Chainlink
]

# See more config options at:
# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options