import {
  TREASURY_EXECUTION_STATUS,
  type TreasuryExecutionStatus,
} from "./status";

const EXECUTION_TRANSITIONS: Record<
  TreasuryExecutionStatus,
  TreasuryExecutionStatus[]
> = {
  CREATED: [
    TREASURY_EXECUTION_STATUS.VALIDATING,
    TREASURY_EXECUTION_STATUS.CANCELLED,
  ],

  VALIDATING: [
    TREASURY_EXECUTION_STATUS.READY_FOR_AUTHORIZATION,
    TREASURY_EXECUTION_STATUS.REQUIRES_INTERVENTION,
    TREASURY_EXECUTION_STATUS.CANCELLED,
  ],

  READY_FOR_AUTHORIZATION: [
    TREASURY_EXECUTION_STATUS.AUTHORIZED,
    TREASURY_EXECUTION_STATUS.CANCELLED,
  ],

  AUTHORIZED: [
    TREASURY_EXECUTION_STATUS.QUEUED,
    TREASURY_EXECUTION_STATUS.CANCELLED,
  ],

  QUEUED: [
    TREASURY_EXECUTION_STATUS.INITIATED,
    TREASURY_EXECUTION_STATUS.FAILED,
    TREASURY_EXECUTION_STATUS.REQUIRES_INTERVENTION,
    TREASURY_EXECUTION_STATUS.CANCELLED,
  ],

  INITIATED: [
    TREASURY_EXECUTION_STATUS.PENDING_EXTERNAL_CONFIRMATION,
    TREASURY_EXECUTION_STATUS.CONFIRMED,
    TREASURY_EXECUTION_STATUS.FAILED,
    TREASURY_EXECUTION_STATUS.REQUIRES_INTERVENTION,
  ],

  PENDING_EXTERNAL_CONFIRMATION: [
    TREASURY_EXECUTION_STATUS.CONFIRMED,
    TREASURY_EXECUTION_STATUS.FAILED,
    TREASURY_EXECUTION_STATUS.REQUIRES_INTERVENTION,
  ],

  CONFIRMED: [TREASURY_EXECUTION_STATUS.REVERSED],

  FAILED: [TREASURY_EXECUTION_STATUS.REQUIRES_INTERVENTION],

  REQUIRES_INTERVENTION: [
    TREASURY_EXECUTION_STATUS.VALIDATING,
    TREASURY_EXECUTION_STATUS.READY_FOR_AUTHORIZATION,
    TREASURY_EXECUTION_STATUS.QUEUED,
    TREASURY_EXECUTION_STATUS.CANCELLED,
  ],

  REVERSED: [],

  CANCELLED: [],
};

export function assertTreasuryExecutionTransition(
  from: TreasuryExecutionStatus,
  to: TreasuryExecutionStatus,
) {
  const allowed = EXECUTION_TRANSITIONS[from] ?? [];

  if (!allowed.includes(to)) {
    throw new Error(`[TREASURY_EXECUTION_TRANSITION_INVALID] ${from} -> ${to}`);
  }
}
