export const TREASURY_EXECUTION_STATUS = {
  CREATED: "CREATED",

  VALIDATING: "VALIDATING",

  READY_FOR_AUTHORIZATION: "READY_FOR_AUTHORIZATION",

  AUTHORIZED: "AUTHORIZED",

  QUEUED: "QUEUED",

  INITIATED: "INITIATED",

  PENDING_EXTERNAL_CONFIRMATION: "PENDING_EXTERNAL_CONFIRMATION",

  CONFIRMED: "CONFIRMED",

  FAILED: "FAILED",

  REQUIRES_INTERVENTION: "REQUIRES_INTERVENTION",

  REVERSED: "REVERSED",

  CANCELLED: "CANCELLED",
} as const;

export type TreasuryExecutionStatus =
  (typeof TREASURY_EXECUTION_STATUS)[keyof typeof TREASURY_EXECUTION_STATUS];
