export const TREASURY_ALLOCATION_STATUS = {
  PROPOSED: "PROPOSED",

  UNDER_REVIEW: "UNDER_REVIEW",

  APPROVED: "APPROVED",

  ACTIVE: "ACTIVE",

  PARTIALLY_CONSUMED: "PARTIALLY_CONSUMED",

  CONSUMED: "CONSUMED",

  RELEASED: "RELEASED",

  CANCELLED: "CANCELLED",
} as const;

export type TreasuryAllocationStatus =
  (typeof TREASURY_ALLOCATION_STATUS)[keyof typeof TREASURY_ALLOCATION_STATUS];
