import {
  TREASURY_INSTRUCTION_STATUS,
  type TreasuryInstructionStatus,
} from "./status";

const INSTRUCTION_TRANSITIONS: Record<
  TreasuryInstructionStatus,
  TreasuryInstructionStatus[]
> = {
  DRAFT: [TREASURY_INSTRUCTION_STATUS.SUBMITTED],

  SUBMITTED: [TREASURY_INSTRUCTION_STATUS.AUTHORITY_REVIEW],

  AUTHORITY_REVIEW: [
    TREASURY_INSTRUCTION_STATUS.AUTHENTICATED,
    TREASURY_INSTRUCTION_STATUS.REQUIRES_CLARIFICATION,
    TREASURY_INSTRUCTION_STATUS.REJECTED,
  ],

  AUTHENTICATED: [TREASURY_INSTRUCTION_STATUS.TREASURY_REVIEW],

  TREASURY_REVIEW: [
    TREASURY_INSTRUCTION_STATUS.APPROVED,
    TREASURY_INSTRUCTION_STATUS.REQUIRES_CLARIFICATION,
    TREASURY_INSTRUCTION_STATUS.REJECTED,
  ],

  REQUIRES_CLARIFICATION: [
    TREASURY_INSTRUCTION_STATUS.AUTHORITY_REVIEW,
    TREASURY_INSTRUCTION_STATUS.CANCELLED,
  ],

  APPROVED: [
    TREASURY_INSTRUCTION_STATUS.FULFILLED,
    TREASURY_INSTRUCTION_STATUS.SUPERSEDED,
    TREASURY_INSTRUCTION_STATUS.CANCELLED,
  ],

  REJECTED: [],

  SUPERSEDED: [],

  CANCELLED: [],

  FULFILLED: [],
};

export function assertTreasuryInstructionTransition(
  from: TreasuryInstructionStatus,
  to: TreasuryInstructionStatus,
) {
  const allowed = INSTRUCTION_TRANSITIONS[from] ?? [];

  if (!allowed.includes(to)) {
    throw new Error(
      `[TREASURY_INSTRUCTION_TRANSITION_INVALID] ${from} -> ${to}`,
    );
  }
}
