export const TREASURY_INSTRUCTION_STATUS = {
  DRAFT: "DRAFT",

  SUBMITTED: "SUBMITTED",

  AUTHORITY_REVIEW: "AUTHORITY_REVIEW",

  AUTHENTICATED: "AUTHENTICATED",

  TREASURY_REVIEW: "TREASURY_REVIEW",

  REQUIRES_CLARIFICATION: "REQUIRES_CLARIFICATION",

  APPROVED: "APPROVED",

  REJECTED: "REJECTED",

  SUPERSEDED: "SUPERSEDED",

  CANCELLED: "CANCELLED",

  FULFILLED: "FULFILLED",
} as const;

export type TreasuryInstructionStatus =
  (typeof TREASURY_INSTRUCTION_STATUS)[keyof typeof TREASURY_INSTRUCTION_STATUS];
