export const PERMISSIONS = {
  ADMIN_ACCESS: 'admin.access',

  PORTAL_ACCESS: 'PORTAL_ACCESS',
  WALLET_INIT: 'WALLET_INIT',
  WALLET_TRANSFER: 'WALLET_TRANSFER',
  INITIATIVE_FUND: 'INITIATIVE_FUND',
  PROJECT_SUBMIT: 'PROJECT_SUBMIT',
  GOVERNANCE_REQUEST: 'GOVERNANCE_REQUEST',

  TREASURY_READ: 'TREASURY_READ',
  TREASURY_ORIGINATE: 'TREASURY_ORIGINATE',
  TREASURY_APPROVE: 'TREASURY_APPROVE',
  TREASURY_QUEUE_PROCESS: 'TREASURY_QUEUE_PROCESS',
  TREASURY_PAUSE: 'TREASURY_PAUSE',
  TREASURY_SYNC: 'TREASURY_SYNC',
  TREASURY_EXECUTE: 'TREASURY_EXECUTE',
  TREASURY_EXECUTE_INTENT: 'TREASURY_EXECUTE_INTENT',
  TREASURY_RUN_AUTONOMOUS_LOOP: 'TREASURY_RUN_AUTONOMOUS_LOOP',

  CONTRACT_READ: 'CONTRACT_READ',
  CONTRACT_SYNC: 'CONTRACT_SYNC',
  CONTRACT_MINT: 'CONTRACT_MINT',
  CONTRACT_PAUSE: 'CONTRACT_PAUSE',

  GOVERNANCE_READ: 'GOVERNANCE_READ',
  GOVERNANCE_PROPOSE: 'GOVERNANCE_PROPOSE',
  GOVERNANCE_VOTE: 'GOVERNANCE_VOTE',
  GOVERNANCE_APPROVE: 'GOVERNANCE_APPROVE',

  SYSTEM_READ_AUDIT: 'SYSTEM_READ_AUDIT',
  SYSTEM_VIEW_REPLAY: 'SYSTEM_VIEW_REPLAY',
  SYSTEM_VIEW_DRIFT: 'SYSTEM_VIEW_DRIFT',
  SYSTEM_MANAGE_AUTH: 'SYSTEM_MANAGE_AUTH',
} as const

export type PermissionKey =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS]